name: Deliver

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: rusk:latest
        build-args: |
          PROTOC_VERSION=${{ vars.PROTOC_VERSION }}
    - name: Save
      run: |
        docker save --output rusk.tar rusk
    - uses: actions/upload-artifact@v3
      with:
        name: image_archive
        path: rusk.tar
